install.packages(tufte)
install.packages(ggplot2)
install.packages(readxl)
install.packages(plotly)
#install.packages(reshape2)
install.packages(gtools)
#install.packages(MASS)
#install.packages(ggridges)
install.packages(pracma)
install.packages(viridis)
install.packages(colorspace)
install.packages(dplyr)
install.packages(tidyr)
system("sudo apt-get -y update")
system("sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev")
install.packages("sf")

