install.packages(tufte)
install.packages(ggplot2)
install.packages(readxl)
install.packages(plotly)
#install.packages(reshape2)
install.packages(gtools)
#install.packages(MASS)
#install.packages(ggridges)
install.packages(pracma)
install.packages(viridis)
install.packages(colorspace)
install.packages(dplyr)
install.packages(tidyr)
install.packages(sf)

